### ISSUE TITLE
Memory Leak from norma-sass install

### ISSUE THREAD

**Issue by edolyne** [NewSpring/Norma#144]
When installing norma-sass, from norma.json, the local install continuously loops.

Packages installed!
Ø Installing packages to your local norma...
Ø Installing the following packages:scss
Ø 
Ø > norma-sass@0.1.2 preinstall /Users/ed.long/Sites/edolyne.com/node_modules/norma-sass
Ø > /usr/bin/env gem install scss-lint
Ø 
Ø 
Ø Successfully installed scss-lint-0.31.0
Ø Parsing documentation for scss-lint-0.31.0
Ø Done installing documentation for scss-lint after 0 seconds
Ø 1 gem installed
Ø 
Ø 
Ø > node-sass@1.2.3 install /Users/ed.long/Sites/edolyne.com/node_modules/norma-sass/node_modules/gulp-sass/node_modules/node-sass
Ø > node scripts/install.js
Ø 
Ø 
Ø Binary downloaded and installed at /Users/ed.long/Sites/edolyne.com/node_modules/norma-sass/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64/binding.node
Ø 
Ø 
Ø > node-sass@1.2.3 postinstall /Users/ed.long/Sites/edolyne.com/node_modules/norma-sass/node_modules/gulp-sass/node_modules/node-sass
Ø > node scripts/build.js
Ø 
Ø 
Ø `darwin-x64` exists; testing
Ø 
Ø Binary is fine; exiting
Ø 
Ø norma-sass@0.1.2 node_modules/norma-sass
Ø ├── run-sequence@1.0.2
Ø ├── minimist@1.1.0
Ø ├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
Ø ├── fs-extra@0.12.0 (jsonfile@2.0.0, rimraf@2.2.8, ncp@0.6.0, mkdirp@0.5.0)
Ø ├── gulp-plumber@0.6.6 (through2@0.6.3)
Ø ├── gulp-cached@1.0.1 (lodash.defaults@2.4.1, through2@0.5.1)
Ø ├── gulp-clip-empty-files@0.1.1 (through2@0.6.3)
Ø ├── gulp-minify-css@0.3.11 (memory-cache@0.0.5, bufferstreams@0.0.2, through2@0.6.3, clean-css@2.2.23)
Ø ├── gulp-if@1.2.5 (gulp-match@0.2.1, through2@0.6.3, ternary-stream@1.2.3)
Ø ├── gulp-combine-media-queries@0.1.0 (css-parse@1.7.0, lodash.defaults@2.4.1, through2@0.4.2, gulp-util@2.2.20)
Ø ├── del@0.1.3 (is-path-cwd@1.0.0, rimraf@2.2.8, each-async@1.1.1, is-path-in-cwd@1.0.0, globby@0.1.1)
Ø ├── gulp-css-validator@0.0.4 (event-stream@3.2.1, css-validator@0.5.1)
Ø ├── gulp-load-plugins@0.7.1 (multimatch@1.0.0, findup-sync@0.1.3)
Ø ├── gulp-util@3.0.1 (lodash._reinterpolate@2.4.1, vinyl@0.4.6, lodash.template@2.4.1, through2@0.6.3, dateformat@1.0.11, multipipe@0.1.2, lodash@2.4.1)
Ø ├── gulp-csscomb@3.0.3 (through2@0.6.3, csscomb@3.0.4)
Ø ├── gulp-scss-lint@0.1.4 (dargs@0.1.0, event-stream@3.1.7, gulp-util@2.2.20, xml2js@0.4.4)
Ø ├── gulp-autoprefixer@1.0.1 (object-assign@1.0.0, through2@0.6.3, vinyl-sourcemaps-apply@0.1.4, autoprefixer-core@3.1.2)
Ø └── gulp-sass@1.2.4 (clone@0.1.19, map-stream@0.1.0, vinyl-sourcemaps-apply@0.1.4, node-sass@1.2.3)

**Comment by jbaxleyiii** [comment]
@edolyne try changing "scss" to "sass" in your package.json
