### ISSUE TITLE
Core - reinstall / update removes files

### ISSUE THREAD

**Issue by edolyne** [NewSpring/Norma#146]
On update Norma asks for your name, even though it was entered during the initial install

**Comment by jbaxleyiii** [comment]
@edolyne can you paste your console output?

**Comment by edolyne** [comment]
➜  edolyne.com git:(master) ✗ norma
Ø Making sure everything is in place...
Ø An update is available for Norma
Ø [?] Would you like to update norma? (Use arrow keys)
[?] Would you like to update norma? yes

Ø > v8flags@1.0.8 install /usr/local/lib/node_modules/normajs/node_modules/gulp/node_modules/v8flags
Ø > node fetch.js
Ø 
Ø 
Ø /usr/local/bin/norma -> /usr/local/lib/node_modules/normajs/bin/norma.js
Ø 
Ø 
Ø > normajs@0.4.13 postinstall /usr/local/lib/node_modules/normajs
Ø > node ./lib/install/post.js
Ø 
Ø 
Ø Ø Thanks for installing me! 
Ø Ø Before we get started, I have a few questions to know how to help you the best...
Ø 
Ø What would you like to be called (name)? 
Ø Ed
Ed
Ø

**Comment by jbaxleyiii** [comment]
It looks like the `npm install normajs --global` is removing all of the contents of the norma directory (including .norma, packages, and scaffolds) so all information is lost. Need to save in a different place (don't like) or store in memory during install and rebuild after.

**Comment by jbaxleyiii** [comment]
This should be fixed
