### ISSUE TITLE
Norma Update Undefined Question

### ISSUE THREAD

**Issue by edolyne** [NewSpring/Norma#154]
When running Norma, there is a notification that an update is available, but the question doesn't have a name so you can not update.

➜  edolyne.com git:(master) ✗ norma
Ø I'm getting everything ready Ed...
Ø Watching files...
Ø [Edolyne] Local access at http://localhost:3000
Ø [Edolyne] Network access at http://10.0.1.15:3000
Ø An update is available for Norma
Ø question must have a name

**Comment by jbaxleyiii** [comment]
@edolyne this is a bug that was introduced 0.5.5 and sadly requires a force update via `npm i -g normajs`

I'm working on a test script to prevent this from breaking on future releases
