### ISSUE TITLE
HAL Easter Egg

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Norma#160]
If a user asks Norma to "open the pod bay doors", she should reply "I'm sorry, [Name]. I'm afraid I can't do that."

**Comment by delianides** [comment]
only if we can have a jurassic park easter egg too. 


![](http://media2.giphy.com/media/5ftsmLIqktHQA/giphy.gif)

**Comment by jbaxleyiii** [comment]
@delianides does terminal support gifs?
