### ISSUE TITLE
Packages names can cause infinite loop

### ISSUE THREAD

**Issue by benwiley** [NewSpring/Norma#175]
![screenshot 2015-02-22 18 46 39](https://cloud.githubusercontent.com/assets/8700223/6321224/359b84aa-bac3-11e4-8f5c-2f24127761a9.png)

I think the NPM package name meteor-load is causing this infinite loop because it is the same as norma-meteor-load just without the norm-

**Comment by jbaxleyiii** [comment]
@bw typically this happens when a package errors out and doesn't return a method. In the above, norma-meteor-load is being installed via npm, but norma's linking isn't working

**Comment by benwiley** [comment]
The issue was with a package that was erroring out. Maybe we need to display the error instead of retrying.
