### ISSUE TITLE
Norma asks if I want to update Norma when I run "norma update"

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Norma#207]
Buggy Behavior: When I run "norma update", it tries to update but also asks me if I want to update Norma with a yes/no choice. If I choose "yes", it then tries to update a second time.

Expected Behavior: When I run "norma update" it just updates Norma.

**Comment by jbaxleyiii** [comment]
@richarddubay what version did you get this behavior on?

**Comment by richarddubay** [comment]
1.6.2 right now. but i've been getting it for a few versions now.

**Comment by jbaxleyiii** [comment]
it should be fixed in 1.6.3 ;)
