### ISSUE TITLE
Task Sequence

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/Norma#219]
Here is how the handlebars and javascript tasks looked in the [NewSpring](https://github.com/NewSpring/NewSpring/blob/feature-norma/Norma#L15-L20) repo:

~~~json
  handlebars:
    src: "assets/_source/vendor/templates/handlebars/**/*"
    dest: "assets/_source/javascripts/"
    order: "pre"
    library: "handlebars" # we still use 1.3.0

  javascript:
    src: "assets/_source/javascripts/**/*"
    dest: "assets/js/"
~~~

I assume the `order: "pre"` declaration was intended to ensure the handlebars templates file was generated before the javascript was compiled. However, in practice this wasn't happening. I had to add the `type: "synchronous"` attribute:

~~~json
  handlebars:
    src: "assets/_source/vendor/templates/handlebars/**/*"
    dest: "assets/_source/javascripts/"
    order: "pre"
    type: "synchronous"
    library: "handlebars" # we still use 1.3.0

  javascript:
    src: "assets/_source/javascripts/**/*"
    dest: "assets/js/"
~~~

This seems to be working. Also, adding `order: "post"` to the javascript task worked, but I'm not sure if the race condition was still there and just not manifesting. 

Are all the `pre` tasks supposed to finish before moving on? Or, does it just kick them off first? Is there a better way to do this? :heart:

**Comment by jbaxleyiii** [comment]
@johnthepink adding the pre should be enough. It looks like the task cb needs to be tabbed on more level here: https://github.com/NewSpring/norma-handlebars/blob/master/package.coffee#L58

**Comment by johnthepink** [comment]
@jbaxleyiii you talking about this?

~~~coffee
  Norma.task "#{name}", (cb) ->

    Norma.execute "#{name}-compile", ->
      Norma.emit "message", "#{name}: ✔ All done!"

      cb null
~~~

I just tried that locally and didn't have any luck. And actually `type: "synchronous"` was only working about half the time. So, I switched to have the javascript task run `post` for now.

**Comment by jbaxleyiii** [comment]
@johnthepink I think the issue is still with the handlebars package. Let me take a look today

**Comment by jbaxleyiii** [comment]
@johnthepink try out this: https://github.com/NewSpring/norma-handlebars/commit/943a01375f0da74f5fa7f3ff83336fa33c351c40

A deploy is going through to npm right now to bump the version as well

**Comment by johnthepink** [comment]
@jbaxleyiii :heart: I'll check it out

**Comment by johnthepink** [comment]
@jbaxleyiii seems to be working well.
