### ISSUE TITLE
Errors from npm warn create false bad exit

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/Norma#222]
@johnthepink found this when doing testing with circleci

**Comment by johnthepink** [comment]
dangit

**Comment by jbaxleyiii** [comment]
@johnthepink I think this only happens on install from the pre install step where Norma ensures your dependencies.

Aka

https://github.com/NewSpring/Norma/blob/master/lib/utilities/manage-dependencies.coffee#L153

which then hits

https://github.com/NewSpring/Norma/blob/master/lib/utilities/promise-spawn.coffee#L35

**Comment by jbaxleyiii** [comment]
This should be fixed now
