### ISSUE TITLE
[2.0] [Discussion] Feature discussion

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/Norma#224]
## General discussion area for 2.0 features and syntax.

Lets do this! @NewSpring/norma @edolyne @johnthepink @edolyne @delianides @richarddubay 

![To the future!](https://media.giphy.com/media/SfMfMAgvL6G1W/giphy.gif)
### Writing Style

Norma 2.0 will be written in ES6 with "use strict" at the top of each file to allow usage of `let` and `class` in scoped blocks. This saves a tremendous overhead of using babel or coffeescript and running Norma as a compile on runtime. This should also encourage other developers in general jumping on as it is just javascript. For style guide information: [ES6 styleguide](https://github.com/NewSpring/docs-javascript-style/tree/master/es6). Fore more discussion see #223 

---
##### Norma Core:

This contains all of the must have methods for norma to run and ensure everything is installed. This is where the real core and helpfulness of Norma comes in. This should be as light weight as possible. Each package should be able to require this core for utility methods.

> We will need to figure out how to share events from packages to the main process Norma

For more discussion see #230
##### Norma CLI:

The cli expands on the main library to give help and completion utilities, to personalize to each developer, and to open and maintain a prompt. This library should hook into the logging side of Norma to pipe outputs from the core library or other components.

For more discussion see #231
##### Norma Developer:

This is a package that can be installed on top of the lightweight norma + norma-cli to provide more methods that help with local development. Auto update utilities, OS notifications, and a system wide norma are the key points of this package. It is like Norma deluxe.

For more discussion see #232
##### Norma system

This is a potential long running Norma process that other apps can connect to. This would be the backbone for the Norma GUI. It would serve to monitor all projects and allow for communication between projects. Think docker server vs docker client || norma system vs norma projects. For more discussion see #225 
##### Norma GUI:

The GUI is a react + meteor application wrapped in electron to provide a GUI for using the system wide Norma brought in by the norma developer package. This handles creating projects, adding packages, starting and stopping projects, and more. This could be expanded to allow for etcd style connections and server env adjustments on the fly. But that is not really the focus. It also provides a great place for reporting progress to developers. The main target for this at launch is no terminal driven devs but rather designer / front-end devs who `just want to build websites`

The GUI for Norma is a pretty exciting project. After seeing the awesomeness of [Yeoman App](https://github.com/yeoman/yeoman-app) and [Kitematic](https://kitematic.com/) as well as coming from a design / front-end background with a healthy fear of the command line, the idea of a great GUI app for Mac, Win10, and Linux came to an early point. This should make starting projects easy! (including downloading from git, adding packages, adding config, and starting apps). My initial thought would be to do this in [Meteor](https://github.com/meteor/meteor) with either Blaze using [Apollos](https://github.com/NewSpring/apollos-core) as a base or React as the rendering engine. However I'm totally open to ideas. For more discussion see: #227
##### Norma server / Norma as a Service

This is probably after 2.0 is stable but should be thought about in development. NAAS (norma as a service) is targeted for local and distributed teams to use. The main feature set is SSO backed keys and config storage, as well as a unified place and auth system for project configuration. CIs, developers, and servers should all be able to access in order to get needed information. It should be easy to add projects, users, and information and manage it. For more discussion see: #229 

Phew, I'm tired already haha.

---
### Methods

One of my favorite things about Norma 1.0 was the ability for packages to act as methods with Norma. This was born out of the limitations of existing build tools (meteor, npm, gulp, etc) which made adding commands more difficult or all together impossible.

Norma CLI will ship with a few needed tools (build, watch, config interaction, etc) but packages should be able to assume methods as well and inherit `this`. This will allow for commands like `norma deploy aws` to be possible just by adding a package. Namespacing will be interesting to figure out. For further discussion see #228 

---
### Packages

Packages are definitely the driving force behind making Norma super easy to use. Norma 2.0 is following Gulp's 4.0 model with the move to Undertaker and I would like to keep up to make it seamless to work between gulp plugins and Norma. An aggressive goal would be to have a shim for Gulpfiles to parse task groupings as well as a shim to allow grunt tasks to be ported.

I would like packages to be able to inherit Norma as the `this` of the module.export. This would make it easier to share process + package events. Should be pretty easy to manage.

We will probably need an upgrade guide from 1.0 to 2.0 if we are dropping automatic support for coffeescript for the sake of speed? For more discussion see #226

**Comment by johnthepink** [comment]
@jbaxleyiii I'm excited about this. Let me know how I can help.
