### ISSUE TITLE
[2.0] [Discussion] Norma File API

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/Norma#234]
When Norma was first started, the api in the Norma file was relatively simple. It had a name, and set of tasks. As time went on, it added tests, environment variables, and now if used as a setting file, it can have any configuration wanted. I think we need to clean up and organize the file API. We also changed languages for the configuration file a few times. It started as JSON, then moved to JSON or CSON, and at one point we had partial support for yaml. I think we need to make a call that will last for a while.
#### Initial thoughts:

Language: [HCL](https://github.com/hashicorp/hcl) ~~via [hden/hcl](https://www.npmjs.com/package/hcl)~~ [NewSpring/node-hcl](https://github.com/NewSpring/node-hcl)?

HCL seems like a great fit to me because it is easy to create great sections, add comments (inline or block), and boolean values can be `true, false, on, off, yes, no`. I think it is a really readable configuration language and it also supports JSON if that is your cup of tea.

``` hcl
# Application
application {
  name =  "My Great Project"
}

environment {
  PORT = 4000
}

bootstrap {
  <unsure>
}

tasks {

  sass {
     version = "0.1.0"
     endpoint = "NewSpring/norma-norma-sass"
     src = "/assets/source"
     dest = "/assets/dest"
     minify = yes
     combine = no
  }

}

tests {
  before = [ ]

  <task name> = {
  }

  after = [ ] 
}
```

@delianides you have the most practice with HCL, thoughts? @benwiley @edolyne @johnthepink 

Also @edolyne I know you had some thoughts re: naming packages vs extending etc. Want to add them here?

**Comment by benwiley** [comment]
@jbaxleyiii While the actual API is important, I believe the documentation of that API is even more important for developer users.  The well documented API allows me, as a developer, to reference and figure out the changes I need to make to my norma file without any added frustration.  

A good example is whenever I would try to setup a new project, I always forgot the syntax/structure for norma-link setup.  But when I visited the readme (https://github.com/NewSpring/Norma-link), I was able to find the folder name, file name, syntax, and a good example of values.

I would even like to have a central documentation location, kind of like meteor.  It could contain norma and "internal" norma package documentation.  This would become difficult once the norma community gets going, but at least the packages we author could be documented there.

**Comment by jbaxleyiii** [comment]
@benwiley I totally agree! Documentation is a huge part of this build out. It is the biggest constraint on the project as it is right now

**Comment by richarddubay** [comment]
@jbaxleyiii @benwiley what would it take to start documenting (allthethings)? This needs to happen badly.

**Comment by johnthepink** [comment]
@richarddubay we need a stenographer

**Comment by richarddubay** [comment]
![giphy-2](https://cloud.githubusercontent.com/assets/3229463/10167716/add9fb38-6697-11e5-83f9-b27e389cdc18.gif)

@johnthepink Like this?

**Comment by jbaxleyiii** [comment]
@delianides @johnthepink @benwiley currently there is not a node parser for HCL :(. Which means we can

* [ ] Not use it and opt for JSON or back to CSON
* [ ] Write our own parser with read + right capabilities (this seems hard but also super super fun)

@NewSpring/norma thoughts?

I'm partial to the adventure of writing a parser because I've never done it before. Plus I think Hashicorp would thing it is cool

**Comment by delianides** [comment]
Wow, that would be a pretty epic parser. HCL is incredibly easier to use and understand. I'd be up for writing the parser if we have the margin with everything else.

**Comment by jbaxleyiii** [comment]
@delianides I think writing it would probably have to be outside of the office as a fun project. I can't see the benefit to our people of writing a parser for a language when we could stick with JSON and keep moving. However most / all of the 2.0 is planned as a pet project right now instead of in office. Mainly because 1.0 works for our needs now and we can keep moving forward with serving our audience.

That being said, I would love for you to give me a rundown of HCL and lets talk through what a parser would look like. Regardless of if it gets used, I'm going to write one I think because I've never written a parser before and it seems like a super fun challenge.

**Comment by jbaxleyiii** [comment]
I've made good progress on a node based [HCL parser](https://github.com/NewSpring/node-hcl). Currently it supports HCL -> JSON for all but nested named blocks, but that will come soon. I also have early support for JSON -> HCL for `Norma.config.save()` methods.

With that as the basis, here are some early thoughts on the Norma file api with examples:

```go
/*

The application node is used to store critical meta data about the project.
This can include the name of the project, the source, the version,
and any other important information.

Norma will use this information when giving logs,
formatting errors / reports, and with the eventual GUI

*/
application {
  name = "NewSpring" // Human readable name of the project
  source = "https://github.com/NewSpring/NewSpring.git" // Source where project code lives
}

/*

Variables represent reusable values that the config / packages
can take advantage of. This will eventually tie into Vault external
storage as well. To use a variable, use the `${variable.variablename} syntax.

Variables can also use the process environment to pull information / set information.

*/
variable {
  source = "assets/_source"
  dest = "assets"
}

/*

The `environment` node is used to configure variables that should be attached to the process
when running Norma to orchestrate your project. These will be piped to any child_process
that is opened by Norma as well. These are like variables but they are exposed to the thread
when running the app.

*/
environment {
  PORT = 4000
}


/*

Groups are a way to join common actions together that can be triggered via Norma commands.
This is similar to how groups are setup with Gulp or Grunt. They can use any task definition
that Norma is aware of for the project. Groups can contain task groupings, custom variables
or variable overwrites, process variables, and more items in the future (like logging levels)

*/
group "application" {
  tasks: [
    "bower", "handlebars", "javascript", "markup", "sass", "copy"
  ]
  variable {
    dest = "application/assets"
  }
}


/*

Like in previous versions of Norma, tasks are still the backbone and the bread and butter of
what makes Norma a helpful assistant. Unlike in previous versions, tasks can be named
uniquely from their package name, and packages can be versioned locked within the
Norma file. I am also proposing a unique namespace for package details to protect package authors from new additions (read features) from conflicting with the config keys they are using.

The package is named by the namespace after the `task` keyword. This will be used to lookup
the package (as norma-<name>) on npm. If there is an overwriting source within the package
namespace, Norma will use this as the source of the package. With this adjustment, packages
can have any name they need to have to make sense for you project.

*/
// simple task with Norma using default configuration for everything
task "copy" {
  src = "${vars.source}/templates/"
  dest = "${vars.dest}/templates/"
}

// Extended task
task "images" {
  package { extend = "copy" }
  src = "${vars.source}/images/"
  dest =  "${vars.dest}/images/"
}

// fully configured task API
task "markup" {
  /*
  
  The reserved `package` node is used to specify overrides / controls to Norma system operations.
  This can include the version, the environment where the package is needed, the order
  it should be run in, the extension of files to watch for, and the source of the package. This is 
  also where tasks can be extended by other tasks.

  */
  package {
    version = "^2.0.0"
    extension = ["html", "haml"]
    environment = "dev"
    order = "pre"
    type = "sync"
    source = "NewSpring/norma-markup"
  }
  
  // package config
  src = "${vars.source}/templates/"
  dest = "${vars.dest}/templates"
}

```

Still to figure out:
* [ ] tests
* [ ] infrastructure (ties to otto?)
* [ ] personalization

**Comment by jbaxleyiii** [comment]
One of the cooler changes with moving to the HCL / terraform model for config is the ability to open up package linking. By exposing tasks to other tasks through interpolation, package can be linked.

For example:

```go

task "copy" {
  source = "${vars.source}/templates/"
  destination = "${vars.destination}/templates/"
}

// Extended task
task "images" {
  package { extend = "copy" }
  source = "${task.copy.source}/images/"
  destination =  "${task.copy.destination}/images/"
}

```
